from bing_image_downloader import downloader

# Define the list of scientific names
scientific_names = [
    'Justicia Adhatoda',
    'Aloe vera',
    'Alpinia speciosa',
    'Andrographis paniculata',
    'Cassia angustifolia',
    'Catharanthus rosea',
    'Cholorophytum borovillianum',
    'Coleus forskolii',
    'Gloriosa superba',
    'Gymnema sylvestre',
    'Hibiscus - rosa sinensis',
    'Lippia nodiflora',
    'Mucuna pruriens',
    'Myristica fragrans',
    'Ocimum sanctum',
    'Phyllanthus amarus',
    'Phyllanthus embilica',
    'Piper nigrum',
    'Stevia rebaudiana',
    'Vetiveria zizanioides',
    'Wedelia chinensis',
    'Withania somnifera (Cultivation)',
    'Abrus precatorius',
    'Abutilon indicum',
    'Acacia sinuata',
    'Acalypha indica',
    'Achyranthes aspera',
    'Acorus calamus',
    'Aegle marmelos',
    'Aerva lanata',
    'Ailanthus excelsa',
    'Alangium salvifolium',
    'Albizia lebbeck',
    'Alpinia galanga',
    'Alstonia scholaris',
    'Alternanthera sessilis',
    'Anona squamosa',
    'Argemone mexicana',
    'Aristolochia bractealata',
    'Aristolochia indica',
    'Aristolochia tagala',
    'Asparagus racemosus',
    'Asteragantha longifolia',
    'Azadirachta indica',
    'Bacopa monnieri',
    'Boerhaavia diffusa',
    'Butea monosperma',
    'Caesalpinia crista',
    'Caesalpinia sappan',
    'Caltropis gigantia',
    'Calotropis procera',
    'Cardiospermum calicacabum',
    'Cassia elata',
    'Cassia auriculata',
    'Cassia fistula',
    'Cassia occidentalis',
    'Cassia tora',
    'Celastrus paniculatus',
    'Centella asiatica',
    'Cichorum intybus',
    'Cinnamomum glaucescens',
    'Cissus quadrangularis',
    'Citrullus colocynthis',
    'Cleome viscosa',
    'Clerodendrum phlomoidis',
    'Clerodendrum serratum',
    'Cocinium fenestratum',
    'Corallocarpus epigaeus',
    'Curculico orchioides',
    'Curcuma aromatica',
    'Cyanodan dactylon',
    'Cyperus rotundus',
    'Datura metal',
    'Decalepis hamiltonii',
    'Desmodium gangeticum',
    'Eclipta alba',
    'Elettaria cardamomum',
    'Embelia ribes',
    'Eugenia jambolana',
    'Euphorbia hirta',
    'Evolvulus alsinoides',
    'Feronia limonia',
    'Ficus benghalensis',
    'Garcinia indica',
    'Gmelina arborea',
    'Gmelina asiatica',
    'Helicteres isora',
    'Heliotropium indicum',
    'Hemidesmus indicus',
    'Holarrhena antidysenterica',
    'Holostemma ada-kodian',
    'Hybanthus enneaspermus',
    'Indigofera tinctoria',
    'Kaempferia galanga',
    'Lawsonia inermis',
    'Lucas aspera',
    'Mangifera indica',
    'Maranta arundinacea',
    'Melia azadirachta',
    'Mesua ferrea'
]

# Download images for each scientific name
for name in scientific_names:
    downloader.download(name, limit=100, output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)
